### ISSUE TITLE
How do I install 4.0-beta1?

### ISSUE THREAD

**Issue by foaly-nr1** [kleijnweb/swagger-bundle#109]
I've been finding it difficult to install the beta version of this bundle. Any pointers?

```bash
$ symfony new sf3 3.4
$ cd sf3
$ composer require kleijnweb/swagger-bundle 4.0-beta1
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: kleijnweb/php-api-descriptions[v1.0.0-alpha5, dev-master].
    - kleijnweb/php-api-hydrator dev-master requires kleijnweb/php-api-descriptions ^v1.0.0-alpha5@dev -> satisfiable by kleijnweb/php-api-descriptions[v1.0.0-alpha5].
    - kleijnweb/swagger-bundle v4.0-beta1 requires kleijnweb/php-api-descriptions dev-master -> satisfiable by kleijnweb/php-api-descriptions[dev-master].
    - kleijnweb/swagger-bundle v4.0-beta1 requires kleijnweb/php-api-hydrator dev-master -> satisfiable by kleijnweb/php-api-hydrator[dev-master].
    - Installation request for kleijnweb/swagger-bundle 4.0-beta1 -> satisfiable by kleijnweb/swagger-bundle[v4.0-beta1].


Installation failed, reverting ./composer.json to its original content.
```

**Note** that minimum stability is set to dev.

**Comment by kleijnweb** [comment]
If you need a bit of temporary stability, I would recommend beta2, since that is locked against specific upstream versions. Otherwise you would have to add the upstream dependencies explicitly, possibly even using revision locks and aliases.

A new beta is coming soon though, as I've been re-hired by the principle user of these bundles. So you might be better off using master right now. 

You can expect stability to increase in the short term, as the client will also require more stability.

**Comment by foaly-nr1** [comment]
Thanks for getting back to me! My bad!

![screen shot 2018-02-05 at 11 02 52](https://user-images.githubusercontent.com/282458/35801402-2e1e1816-0a64-11e8-9383-66efc80e929c.png)
