### ISSUE TITLE
Make ExceptionListener optional

### ISSUE THREAD

**Issue by kleijnweb** [kleijnweb/swagger-bundle#47]
Some people might want to use their own Exception Listener, it should be easy to disable.

**Comment by foaly-nr1** [comment]
Have you closed this because you changed your mind or because there was no pull request?

I'm looking for a way to limit this bundle's impact on parts of my application that are not managed by it.

**Comment by kleijnweb** [comment]
It's a while ago so I'm not sure. I regret not leaving a comment. I am in favor of it though. Should be easy too. Note though that in master (4.0-BETA) you can already override "kernel.listener.swagger.exception" since it is marked as public.

**Comment by foaly-nr1** [comment]
I'm thinking of adding a compiler pass to remove the listeners based on the current route so not to interfere with the rest of the application.

Alternatively, what do you think of https://github.com/kleijnweb/swagger-bundle/pull/104?

**Comment by kleijnweb** [comment]
> I'm thinking of adding a compiler pass to remove the listeners based on the current route so not to interfere with the rest of the application.

That doesn't sound like it would work, as the request is in a separate container scope. Good thing too, otherwise the container would have to be rebuilt for every request.

Having the listeners skip processing of non-swagger requests as in your PR seems like way to go. I think 3.x already does that properly and I broke it in 4.0. So your PR is very welcome :)

If you also wanted to add a mechanism to completely disable the exception handler, you could add something like this:

```php
 if (!$config['disable_exception_listener']) {
     $loader->load('some_file_with_relevant_definitions.yml');
}
```

I think a more common use case would to override the exception handler definition though, since you probably want _some_ exception handler.

I should probably document that.

**Comment by foaly-nr1** [comment]
I've looked into Symfony's error handling. The debug component handles some exceptions in [ExceptionHandler:handle](https://github.com/symfony/debug/blob/3.4/ExceptionHandler.php#L106), e.g. ensures `NotFoundHttpException` leads to 404 instead of 500.

If installed, the Twig bundle handles exceptions in a more elaborate manner in [ExceptionController:show](https://github.com/symfony/twig-bundle/blob/3.4/Controller/ExceptionController.php#L55):
> Look for a template for the given format and status code (like error404.json.twig or error500.html.twig);
> — https://symfony.com/doc/current/controller/error_pages.html#overriding-the-default-error-templates

I suggest to always limit `ViewListener` and `RequestListener` to routes managed by the bundle, as per https://github.com/kleijnweb/swagger-bundle/pull/104. However, limiting `ExceptionListener` would mean that 404 won't be handled as obviously a route that doesn't exist isn't managed by the bundle.

I agree we should add add an option to the config tree instead with default `true`:
```yaml
swagger:
    listeners:
        exception: true
```

**Comment by kleijnweb** [comment]
Makes sense. But since the other listeners don't require any config, maybe simply:

```yaml
swagger:
  handle_exceptions: true
```

would make more sense.

**Comment by foaly-nr1** [comment]
Agreed, done.

**Comment by kleijnweb** [comment]
Awesome, thanks :)
